import React from 'react'
import { StyleSheet } from 'react-native'

export const AlertStyles = StyleSheet.create({
    container: { 
      flex: 1,
      backgroundColor: '#FFF',
      alignItems: 'stretch',
      justifyContent: 'flex-start',
    },
    title: {
      fontSize: 20,
      fontWeight: 'bold',
    },
    sectionHeading: {
      color: '#FFF',
      alignItems: 'center',
      textAlign: 'center',
      marginLeft: 16,
      justifyContent: 'center',
      fontWeight: 'bold',
      fontSize: 20,
      marginBottom: 4,
    },
    sectionText: {
      color: 'black',
      alignItems: 'center',
      textAlign: 'center',
      width: '90%',
      marginLeft: 16,
      justifyContent: 'center',
      //fontFamily: 'Verdana',
      fontWeight: 'normal',
      fontSize: 14,
      marginBottom: 20,
    },
    separator: {
      marginVertical: 30,
      height: 1,
      width: '80%',
    },
    logo: {
      fontWeight: 'bold',
      fontSize: 50,
      color: 'black',
      marginBottom: 40,
    },
    Heading: {
      flex: 1,
      color: '#8EC064',
      alignItems: 'flex-start',
      textAlign: 'center',
      justifyContent: 'flex-start',
      fontWeight: 'bold',
      fontSize: 36,
      marginBottom: 5,
      marginTop: 10,
    },
    subheading: {
      flex: 1,
      color: '#8EC064',
      alignItems: 'flex-start',
      textAlign: 'center',
      justifyContent: 'center',
      fontWeight: 'bold',
      fontSize: 24,
    },
    sectionCard: {
      backgroundColor: '#8EC064',
      borderColor: '#8EC064',
      borderRadius: 25,
      shadowRadius: 25,
    },
    descriptionText: {
      flex: 1,
      fontWeight: 'bold',
      //fontFamily: 'Verdana',
      alignSelf: 'center',
      textAlign: 'center',
      color: '#FFF',
      width: '80%',
      fontSize: 20,
    },
  })