import { StyleSheet } from 'react-native'

export const DescriptionStyles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#FFF' },
    ParkHeading: {
      flex: 1,
      color: '#8EC064',
      alignItems: 'center',
      textAlign: 'center',
      justifyContent: 'center',
      fontWeight: 'bold',
      fontSize: 36,
      marginBottom: 5,
      marginTop: 10,
    },
    sectionHeading: {
      flex: 1,
      color: '#000',
      alignItems: 'center',
      textAlign: 'center',
      marginLeft: 16,
      justifyContent: 'center',
      fontWeight: 'bold',
      fontSize: 24,
      marginBottom: 4,
    },
    sectionText: {
      flex: 1,
      color: '#000',
      alignItems: 'center',
      textAlign: 'center',
      width: '90%',
      marginLeft: 16,
      justifyContent: 'center',
      //fontFamily: 'Verdana',
      fontWeight: 'normal',
      fontSize: 14,
      marginBottom: 20,
    },
    descriptionText: {
      flex: 1,
      fontWeight: 'bold',
      //fontFamily: 'Verdana',
      alignSelf: 'center',
      textAlign: 'center',
      color: '#000',
      width: '80%',
      fontSize: 14,
      marginBottom: 30,
    },
    sectionCard: {
      backgroundColor: '#8EC064',
      borderColor: '#8EC064',
      borderRadius: 25,
      shadowRadius: 25,
    },
    weather: {
      marginTop: 40,
    },
  })